# Generated by Django 5.0.6 on 2025-10-07 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_wishlist_delete_category'),
    ]

    operations = [
    ]
