# Generated by Django 5.0.6 on 2025-10-07 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20251007_1416'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
