# Generated by Django 5.0.6 on 2025-10-07 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_order_orderitem_order_products'),
    ]

    operations = [
    ]
